### ISSUE TITLE
JSON format returns RDF

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/registry-deploy-testenv#2]
Accessing `http://environment-registry.epimorphics.net/registry/def/test/?_format=json` returns an RDF/XML document

**Comment by der** [comment]
Format `json` is not currently support. Only `jsonld`. The choice of naming is to allow for a more idiomatic json option in the future.

At the moment `_format` is treated as weighting the format away from the default (RDF/XML) rather than an override. It may be possible to change that so as to force a return of 406 instead in this case. However, unless it would make a significant difference I would rather punt on that for now.

**Comment by ijdickinson** [comment]
I have just discovered that I need to set the  `Accept` header as well as the `_format` param. The default conneg string for Axios is `application/json, text/plain, */*`, but I only started getting consistent results by setting the `Accept` header to the mime type matching the `format`. If that's the expected behaviour (which is reasonable), it might be worth mentioning in the docs.

**Comment by der** [comment]
Hmm. You shouldn't need to set an accept header at all, e.g.

    curl -i "http://environment-registry.epimorphics.net/registry/def/test/?_format=jsonld"

Returns jsonld just fine.

However, setting an explicit accept header of "application/json" does seem to be returning some non-jsonld json, will investigate further.

**Comment by ijdickinson** [comment]
Closing as obsolete
